#!/bin/bash

set -e
set -o pipefail
set -u

main() {
  local role="${BUILDKITE_PLUGIN_SSM_ASSUME_ROLE_ARN:-}"
  local build="${BUILDKITE_BUILD_NUMBER:-}"

  if [[ -n $role && -n $build ]]; then
    echo "~~~ Assuming IAM role $role ..."
    eval "$(assume_role_credentials "$role" "$build" | credentials_json_to_shell_exports)"

    echo "Exported session credentials:"
    echo "  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    echo "  AWS_SECRET_ACCESS_KEY=(${#AWS_SECRET_ACCESS_KEY} chars)"
    echo "  AWS_SESSION_TOKEN=(${#AWS_SESSION_TOKEN} chars)"
  else
    echo "Missing BUILDKITE_PLUGIN_SSM_ASSUME_ROLE_ARN or BUILDKITE_BUILD_NUMBER"
  fi

  local awsregion=${AWS_DEFAULT_REGION:-ap-southeast-2}
  local ssmkey="${BUILDKITE_PLUGIN_SSM_SSMKEY:-}"
  local exportname="${BUILDKITE_PLUGIN_SSM_EXPORTNAME:-}"
  ssm_get_parameter "$ssmkey" "$awsregion" "$exportname"

}

# Assume the IAM role $1, allocate a session name derived from $2.
# output: the Credentials portion of the AWS response JSON;
#     {
#         "SecretAccessKey": "foo"
#         "SessionToken": "bar",
#         "Expiration": "...",
#         "AccessKeyId": "baz"
#     }
assume_role_credentials() {
  local role="$1"
  local build="$2"
  aws sts assume-role \
    --role-arn "$role" \
    --role-session-name "aws-assume-role-buildkite-plugin-${build}" \
    --query Credentials
}

# Convert credentials JSON to shell export statements using standard CLI tools
# input:
#     {
#         "SecretAccessKey": "foo"
#         "SessionToken": "bar",
#         "Expiration": "...",
#         "AccessKeyId": "baz"
#     }
# output:
#     export AWS_SECRET_ACCESS_KEY="foo"
#     export AWS_SESSION_TOKEN="bar"
#     export AWS_ACCESS_KEY_ID="baz"
credentials_json_to_shell_exports() {
  sed \
    -e 's/ *"\(.*\)": \(".*"\),*/\1=\2/g' \
    -e 's/^SecretAccessKey/export AWS_SECRET_ACCESS_KEY/' \
    -e 's/^AccessKeyId/export AWS_ACCESS_KEY_ID/' \
    -e 's/^SessionToken/export AWS_SESSION_TOKEN/' \
    | grep "^export AWS"
}


# Retieve the SSM Parameter $1, using the region defined in $2.
# output: the SSM Key, Value as an environment variable;
# output: export MySecret=MyValue
#   {
#       "InvalidParameters": [],
#       "Parameters": [
#           {
#               "Type": "String",
#               "Name": "/MySecret",
#               "Value": "MyValue"
#           }
#       ]
#   }
ssm_get_parameter() {
    local ssmkey="$1"
    local awsregion="$2"
    local exportname="$3"
    echo "--- :ssm: Get SSM /buildkite/${ssmkey} in region ${awsregion}"
    ssmValue=$(aws ssm get-parameter --region "$awsregion" --name "/buildkite/$ssmkey" --with-decryption --query Parameter.Value --output text)
    rc=$?
    #echo "--- :ssm: SSM value ${ssmValue}"

    # fail fast
    if [[ ! $rc -eq 0 ]]; then
        echo "Command failed: The parameter '/buildkite/$ssmkey' does not exist or another error occurred."
        exit 1
    fi

    if [[ -n "${exportname:-}" ]]; then
        echo "Using custom export name specified ${exportname}"
        export "$exportname"="$ssmValue"
    else
        echo "Using ssm key name to export variable ${ssmkey}"
        export "$ssmkey"="$ssmValue"
    fi
}

main
